!PRINT 9X9 PRODUCTS LIST
!2017.01.18 WWY
    PROGRAM PRODUCT
    	DO i = 1, 9
    		DO k = 1, i 
    			WRITE (*, '(I5, 4X, \)') i * k ! THE TERM '\' MAKE LINKING TWO LINES 
    		END DO
    		WRITE(*, *) !INTERRUPT THE LINE, CURSOR BEGIN AT THE NEW LINE
    	END DO
    END PROGRAM PRODUCT